version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /ssl/rpi4apps.local.pem:/etc/ssl/certs/rpi4apps.local.pem
      - /ssl/rpi4apps.local-key.pem:/etc/ssl/certs/rpi4apps.local-key.pem

  vault-app:
    container_name: vault-app
    build: .
    restart: unless-stopped
    expose:
      - 3030
    env_file:
      - /home/pi/apps/envs/vault_envs
